export const GITHUB_OAUTH_ENDPOINT_CLIENT_ID_PARAMETER_KEY = "client_id";
export const GITHUB_OAUTH_ENDPOINT_CLIENT_ID_PARAMETER_VALUE =
  "a32bff5481e58da992c4";
export const GITHUB_OAUTH_ENDPOINT_SCOPE_PARAMETER_KEY = "scope";
export const GITHUB_OAUTH_ENDPOINT_SCOPE_PARAMETER_VALUE = "repo";
export const GITHUB_OAUTH_ENDPOINT_STATE_PARAMETER_KEY = "state";
