const USERS_SERVICE_API = `http://${process.env.REACT_APP_USER_SERVICE_HOST}:${process.env.REACT_APP_USER_SERVICE_PORT}/api`;
const DEPLOYMENTS_SERVICE_API = `http://${process.env.REACT_APP_DEPLOYMENT_SERVICE_HOST}:${process.env.REACT_APP_DEPLOYMENT_SERVICE_PORT}/api`;
const USER_ID = "1";

export { USERS_SERVICE_API, DEPLOYMENTS_SERVICE_API, USER_ID };
